// @ts-check
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import lastmodByPath from './src/data/page-lastmod.json' with { type: 'json' };

const SITE = 'https://precisionsolutionstech.com';

export default defineConfig({
  site: SITE,
  trailingSlash: 'always',
  integrations: [
    sitemap({
      // Per-page <lastmod>, generated by scripts/gen-lastmod.mjs. A page with
      // no entry ships without lastmod on purpose — omitting it says nothing,
      // where guessing says something false.
      serialize(item) {
        const path = new URL(item.url).pathname;
        const lastmod = /** @type {Record<string, string>} */ (lastmodByPath)[path];
        if (lastmod) item.lastmod = `${lastmod}T00:00:00+00:00`;
        return item;
      },
    }),
  ],
  build: {
    format: 'directory',
  },
});
